export const contentSize = {
  MAIN_CONTENT_SHEET_SIZE: 1150,

  AYALYSIS_FILTER_GROUP_HEIGHT: 50,

  SUMMONER_INFO_SHEET_HEIGHT: 250,
  SUMMONER_INFO_ICON_HEIGHT: 120,
  SUMMONER_VIEW_SELECT_HEIGHT: 45,

  SUMMONER_TOTAL_TIER_HEIGHT: 100,
  SUMMONER_TOTAL_TIER_WIDTH: 300,
  SUMMONER_TOTAL_TIER_MORE_HEIGHT: 100,

  SUMMONER_TOTAL_TIER_CHAMPIONS_HEIGHT:400,

  SUMMONER_TOTAL_MATCHES_FILTER_HEIGHT: 35,
  SUMMONER_TOTAL_MATCHES_WIDTH: 825,
  // SUMMONER_TOTAL_MATCHES_HEIGHT: 1000,

  SUMMONER_TOTAL_MATCHES_RECENT_HEIGHT: 170,
  SUMMONER_TOTAL_MATCH_HEIGHT: 102,

  SUMMONER_TOTAL_MATCH_SEEMORE_HEIGHT: 550,
  SUMMONER_TOTAL_MATCH_SEEMORE_LINK_HEIGHT: 35,
  SUMMONER_TOTAL_MATCH_SEEMORE_FILTER_HEIGHT: 45,

  CHAMPION_ICON_SIZE: 54,
  ITEM_ICON_SIZE: 22,
  SPELL_ICON_SIZE: 23,
  ENTRY_SPELL_ICON_SIZE: 16,

  CHAMPION_ENTRIES_ICON_SIZE: 18
}

export const urlConfig = {
  baseUrl: 'https://kr.api.riotgames.com',
  asiaUrl: 'https://asia.api.riotgames.com',
  imgUrl: 'https://ddragon.leagueoflegends.com/cdn'
}