export const contentSize = {
  MAIN_CONTENT_SHEET_SIZE: 1150,

  AYALYSIS_FILTER_GROUP_HEIGHT: 50,

  SUMMONER_INFO_SHEET_HEIGHT: 250,
  SUMMONER_INFO_ICON_HEIGHT: 120,
  SUMMONER_VIEW_SELECT_HEIGHT: 45,

  SUMMONER_TOTAL_TIER_HEIGHT: 100,
  SUMMONER_TOTAL_TIER_WIDTH: 300,
  SUMMONER_TOTAL_TIER_MORE_HEIGHT: 100,

  SUMMONER_TOTAL_TIER_CHAMPIONS_HEIGHT:400,

  SUMMONER_TOTAL_MATCHES_FILTER_HEIGHT: 35,
  SUMMONER_TOTAL_MATCHES_WIDTH: 825,
  SUMMONER_TOTAL_MATCHES_HEIGHT: 1000

}